import type { RunState, TileState } from '../types';
import { allTiles, neighbors, recomputeAdjacent } from './board';
import { chance, pick } from './rng';
export function countItem(run:RunState, itemId:string): number { return run.player.items.find(i=>i.itemId===itemId)?.stacks ?? 0; }
export function hasItem(run:RunState, itemId:string): boolean { return countItem(run,itemId)>0; }
export function addItem(run:RunState, itemId:string){ if(itemId==='breakfast_ration'){ run.player.hp=Math.min(run.player.maxHp, run.player.hp+1); return; } const inv=run.player.items.find(i=>i.itemId===itemId); if(inv) inv.stacks++; else run.player.items.push({itemId,stacks:1}); if(itemId==='reinforced_vest'){run.player.maxHp++; run.player.hp++;} }
export function getMineDamage(run:RunState): number { return hasItem(run,'saint_barbaras_lantern') ? 0 : 1; }
export function getTreasureGoldMultiplier(run:RunState): number { let m=1 + .25*countItem(run,'coin_magnet'); if(hasItem(run,'greed_engine')) m+=1; if(hasItem(run,'dragons_hoard_contract')) m+=3; if(run.modifier.id==='dense_veins') m+=.5; return m; }
export function getExitThreshold(run:RunState): number { let t=.65 - .05*countItem(run,'rope_coil') - (hasItem(run,'exit_dowsing_rod')?.15:0); if(run.player.floor===10 && hasItem(run,'last_descent')) t=.4; return Math.max(.35,t); }
export function adjustedMineCount(run:Pick<RunState,'floorConfig'|'modifier'|'player'>): number { let pct=run.floorConfig.minePercent; if(run.modifier.id==='dense_veins') pct += .10; if(run.player.items.some(i=>i.itemId==='greed_engine')) pct+=.05; if(run.player.items.some(i=>i.itemId==='dragons_hoard_contract')) pct+=.08; pct=Math.min(.35,pct); return Math.floor(run.floorConfig.width*run.floorConfig.height*pct); }
export function onStartFloor(run:RunState){ run.floorStats={revealedSafe:0,damageTaken:false,luckyBootsUsed:false,hourglassUsed:false,carefulHandsUsed:false,runeUsed:false,trapEaterUsed:false,lastDescentUsed:false,insuranceUsed:false,unstableUsed:false,crackedCount:0,safeRevealsSinceArmor:0,goldCollected:0,minesTriggered:0}; run.player.armor=countItem(run,'blast_shield'); run.player.scanCharges=countItem(run,'spare_lantern'); run.player.revealCharges=countItem(run,'surveyors_chalk'); }
export function applyMineDamage(run:RunState, tile:TileState, log:string[]): boolean { tile.exploded=true; run.floorStats.minesTriggered++; run.player.score-=50; if(hasItem(run,'timeworn_hourglass')&&!run.floorStats.hourglassUsed){ run.floorStats.hourglassUsed=true; tile.revealed=false; tile.exploded=false; tile.dangerMarked=true; log.push('Timeworn Hourglass rewound the blast.'); return true; } if(hasItem(run,'lucky_boots')&&!run.floorStats.luckyBootsUsed){ run.floorStats.luckyBootsUsed=true; log.push('Lucky Boots absorbed the blast.'); return true; } if(run.player.floor===10&&hasItem(run,'last_descent')&&!run.floorStats.lastDescentUsed){ run.floorStats.lastDescentUsed=true; log.push('The Last Descent swallowed the blast.'); return true; } let dmg=getMineDamage(run); if(dmg===0){ log.push('Saint Barbara’s Lantern reduced the blast to sparks.'); return true; } if(run.player.armor>0){ const used=Math.min(run.player.armor,dmg); run.player.armor-=used; dmg-=used; } if(dmg>0){ run.player.hp-=dmg; run.floorStats.damageTaken=true; log.push(`A trap exploded. -${dmg} HP.`); if(hasItem(run,'miners_insurance')&&!run.floorStats.insuranceUsed){ const gold=10*countItem(run,'miners_insurance'); run.player.gold+=gold; run.floorStats.insuranceUsed=true; log.push(`Miner’s Insurance paid ${gold} gold.`); } } if(run.player.hp<=0 && hasItem(run,'phoenix_canteen')){ const inv=run.player.items.find(i=>i.itemId==='phoenix_canteen'); if(inv){ run.player.hp=1; run.player.items=run.player.items.filter(i=>i.itemId!=='phoenix_canteen'); log.push('Phoenix Canteen restored you to 1 HP.'); return true; }} if(run.player.hp<=0){ run.status='lost'; run.finalResult='defeat'; return false; } return true; }
export function markStartHints(run:RunState){ const mines=allTiles(run.board).filter(t=>t.kind==='mine'&&!t.dangerMarked); for(let i=0;i<countItem(run,'pocket_map')&&mines.length;i++) pick(run.rng,mines).dangerMarked=true; const safe=allTiles(run.board).filter(t=>t.kind!=='mine'&&!t.revealed); const ghostCount=countItem(run,'oracle_stone')*3 + (hasItem(run,'perfect_map')?Math.ceil(safe.length*.1):0); for(const t of safe.sort(()=>run.rng.seed%2?1:-1).slice(0,ghostCount)) t.ghostNumber=t.adjacentMines; }
export function onSafeReveal(run:RunState,tile:TileState,log:string[]){ run.floorStats.revealedSafe++; run.floorStats.safeRevealsSinceArmor++; run.player.score+=10; if(tile.adjacentMines>0){ let fogChance=run.modifier.id==='fogged_numbers'?.2:0; if(hasItem(run,'lantern_oil')) fogChance*=.5; tile.fogged=fogChance>0 && chance(run.rng,fogChance); if(run.modifier.id==='cracked_lantern'&&run.floorStats.crackedCount<3){ run.floorStats.crackedCount++; tile.forgotten=true; }} if(hasItem(run,'heart_of_quartz')&&run.floorStats.safeRevealsSinceArmor>=20){ run.player.armor+=countItem(run,'heart_of_quartz'); run.floorStats.safeRevealsSinceArmor=0; log.push('Heart of Quartz granted armor.'); } if(run.modifier.id==='unstable_ground'&&!run.floorStats.unstableUsed&&tile.adjacentMines===0){ const candidates=allTiles(run.board).filter(t=>!t.revealed&&!t.flagged&&t.kind==='normal'); if(candidates.length){ const c=pick(run.rng,candidates); c.kind='mine'; run.board.mineCount++; recomputeAdjacent(run.board); run.floorStats.unstableUsed=true; log.push('Unstable ground shifted: a safe tile became a trap.'); }} }
export function onFloorClear(run:RunState){ const correct=allTiles(run.board).filter(t=>t.flagged&&t.kind==='mine').length; const incorrect=allTiles(run.board).filter(t=>t.flagged&&t.kind!=='mine').length; run.player.score += 100 + correct*(25 + 15*countItem(run,'flag_bundle')) - incorrect*10; if(hasItem(run,'deep_focus')&&!run.floorStats.damageTaken){ run.player.maxHp++; run.player.hp++; } }
