import { describe, expect, it } from 'vitest';
import { createRun, gameReducer, initialGameState } from './run';
import { allTiles, createBoard, getTile, recomputeAdjacent } from './board';
import { revealTile } from './reveal';
import { toggleFlag } from './flag';
import { chordTile } from './chord';
import { applyMineDamage, addItem } from './effects';
import { generateRewards } from './loot';
import { buyItem } from './shop';
import { DEFAULT_SAVE, loadSave, saveData } from './persistence';

function log(){ return [] as string[]; }
function basicRun(){ return createRun(DEFAULT_SAVE, 12345); }

describe('Depthsweeper engine', () => {
 it('first click never places a mine on clicked tile', () => { const run=basicRun(); revealTile(run,3,3,log()); expect(getTile(run.board,3,3)?.kind).not.toBe('mine'); });
 it('first click excludes adjacent mines', () => { const run=basicRun(); revealTile(run,3,3,log()); expect(run.board.tiles.flat().filter(t=>Math.max(Math.abs(t.x-3),Math.abs(t.y-3))<=1).every(t=>t.kind!=='mine')).toBe(true); });
 it('adjacent mine counts are correct', () => { const run=basicRun(); run.board=createBoard(3,3,0); getTile(run.board,0,0)!.kind='mine'; getTile(run.board,2,2)!.kind='mine'; recomputeAdjacent(run.board); expect(getTile(run.board,1,1)?.adjacentMines).toBe(2); expect(getTile(run.board,2,1)?.adjacentMines).toBe(1); });
 it('revealing zero recursively reveals safe region', () => { const run=basicRun(); run.board=createBoard(4,4,1); run.board.generated=true; getTile(run.board,3,3)!.kind='mine'; recomputeAdjacent(run.board); revealTile(run,0,0,log()); expect(getTile(run.board,0,0)?.revealed).toBe(true); expect(getTile(run.board,1,1)?.revealed).toBe(true); });

 it('recursive zero reveal does not reveal or damage through mines', () => { const run=basicRun(); run.board=createBoard(4,4,1); run.board.generated=true; getTile(run.board,3,3)!.kind='mine'; recomputeAdjacent(run.board); revealTile(run,0,0,log()); expect(getTile(run.board,3,3)?.revealed).toBe(false); expect(run.player.hp).toBe(3); });
 it('recursive zero reveal does not trigger trapped treasure damage', () => { const run=basicRun(); run.board=createBoard(3,3,0); run.board.generated=true; const treasure=getTile(run.board,1,1)!; treasure.kind='treasure'; treasure.trappedTreasure=true; recomputeAdjacent(run.board); revealTile(run,0,0,log()); expect(treasure.revealed).toBe(true); expect(run.player.hp).toBe(3); });
 it('generated treasure tiles are safe and never mines', () => { const run=basicRun(); revealTile(run,2,2,log()); const treasures=allTiles(run.board).filter(t=>t.kind==='treasure'); expect(treasures.length).toBeGreaterThan(0); expect(treasures.every(t=>t.kind!=='mine'&&!t.exploded)).toBe(true); });
 it('flagged tile cannot be revealed', () => { const run=basicRun(); run.board=createBoard(3,3,0); run.board.generated=true; toggleFlag(run,1,1,log()); revealTile(run,1,1,log()); expect(getTile(run.board,1,1)?.revealed).toBe(false); });
 it('chording works with correct flags', () => { const run=basicRun(); run.board=createBoard(3,3,1); run.board.generated=true; getTile(run.board,0,0)!.kind='mine'; recomputeAdjacent(run.board); getTile(run.board,1,1)!.revealed=true; toggleFlag(run,0,0,log()); chordTile(run,1,1,log()); expect(getTile(run.board,2,2)?.revealed).toBe(true); });
 it('chording can trigger mine with incorrect flags', () => { const run=basicRun(); run.board=createBoard(3,3,1); run.board.generated=true; getTile(run.board,0,0)!.kind='mine'; recomputeAdjacent(run.board); getTile(run.board,1,1)!.revealed=true; toggleFlag(run,2,2,log()); chordTile(run,1,1,log()); expect(getTile(run.board,0,0)?.revealed).toBe(true); expect(run.player.score).toBeLessThan(50); });
 it('mine damage reduces armor before HP', () => { const run=basicRun(); run.player.armor=1; const mine=getTile(run.board,0,0)!; mine.kind='mine'; mine.revealed=true; applyMineDamage(run,mine,log()); expect(run.player.armor).toBe(0); expect(run.player.hp).toBe(3); });
 it('Lucky Boots prevents first mine damage once per floor', () => { const run=basicRun(); addItem(run,'lucky_boots'); const a=getTile(run.board,0,0)!; a.kind='mine'; a.revealed=true; applyMineDamage(run,a,log()); expect(run.player.hp).toBe(3); const b=getTile(run.board,1,0)!; b.kind='mine'; b.revealed=true; applyMineDamage(run,b,log()); expect(run.player.hp).toBe(2); });
 it('exit appears after threshold', () => { const run=basicRun(); addItem(run,'exit_dowsing_rod'); run.board=createBoard(3,3,0); run.board.generated=true; run.floorStats.revealedSafe=3; revealTile(run,0,0,log()); revealTile(run,1,0,log()); expect(run.board.exitAvailable || run.board.exitPlaced || run.status==='won').toBe(true); });
 it('revealing exit clears floor', () => { let state=gameReducer(initialGameState,{type:'START_RUN'}); const run=state.run!; run.board=createBoard(2,2,0); run.board.generated=true; run.board.exitPlaced=true; run.board.exitAvailable=true; getTile(run.board,0,0)!.kind='exit'; state={...state,run}; state=gameReducer(state,{type:'REVEAL_TILE',x:0,y:0}); expect(state.phase).toBe('reward'); });
 it('reward generation returns valid unlocked items', () => { const run=basicRun(); const rewards=generateRewards(run,{...DEFAULT_SAVE,unlockedItems:[]}); expect(rewards).toHaveLength(3); expect(rewards.every(i=>i.rarity==='common'||i.rarity==='uncommon')).toBe(true); });
 it('duplicate non-stackable items are not offered if already owned', () => { const run=basicRun(); addItem(run,'lucky_boots'); const rewards=Array.from({length:20},()=>generateRewards(run,{...DEFAULT_SAVE,unlockedItems:['rare','legendary']})).flat(); expect(rewards.some(i=>i.id==='lucky_boots')).toBe(false); });
 it('shop buy subtracts gold and adds item', () => { const run=basicRun(); run.player.gold=100; expect(buyItem(run,'breakfast_ration')).toBe(true); expect(run.player.gold).toBe(85); });

 it('start-of-floor scan and reveal charges reset instead of accumulating', () => { let state=gameReducer(initialGameState,{type:'START_RUN'}); const run=state.run!; addItem(run,'spare_lantern'); addItem(run,'surveyors_chalk'); run.player.scanCharges=0; run.player.revealCharges=0; run.status='won'; state={...state,run}; state=gameReducer(state,{type:'REVEAL_TILE',x:0,y:0}); state=gameReducer(state,{type:'CHOOSE_REWARD',itemId:'breakfast_ration'}); expect(state.run!.player.scanCharges).toBe(1); expect(state.run!.player.revealCharges).toBe(1); state.run!.player.scanCharges=0; state.run!.player.revealCharges=0; state.run!.status='won'; state=gameReducer(state,{type:'REVEAL_TILE',x:0,y:0}); state=gameReducer(state,{type:'CHOOSE_REWARD',itemId:'breakfast_ration'}); expect(state.run!.player.scanCharges).toBe(1); expect(state.run!.player.revealCharges).toBe(1); });
 it('reward rerolls are use-it-or-lose-it per reward screen', () => { let state=gameReducer(initialGameState,{type:'START_RUN'}); const run=state.run!; addItem(run,'tinkers_kit'); run.status='won'; state={...state,run}; state=gameReducer(state,{type:'REVEAL_TILE',x:0,y:0}); expect(state.phase).toBe('reward'); expect(state.run!.player.rerolls).toBe(1); state=gameReducer(state,{type:'CHOOSE_REWARD',itemId:'breakfast_ration'}); expect(state.run!.player.rerolls).toBe(0); state.run!.status='won'; state=gameReducer(state,{type:'REVEAL_TILE',x:0,y:0}); expect(state.run!.player.rerolls).toBe(1); });
 it('buying a shop item removes it from current shop choices', () => { let state=gameReducer(initialGameState,{type:'START_RUN'}); const run=state.run!; run.player.gold=100; state={...state,run,phase:'shop',shopItems:[{ id:'breakfast_ration', name:'Breakfast Ration', rarity:'common', type:'consumable', description:'Heal 1 HP immediately, not above max HP.', price:15 }]}; state=gameReducer(state,{type:'BUY_ITEM',itemId:'breakfast_ration'}); expect(state.run!.player.gold).toBe(85); expect(state.shopItems.some(item=>item.id==='breakfast_ration')).toBe(false); });
 it('save data persists and loads', () => { const store:Record<string,string>={}; const storage={getItem:(k:string)=>store[k]??null,setItem:(k:string,v:string)=>{store[k]=v;}}; saveData({...DEFAULT_SAVE,totalRuns:7},storage); expect(loadSave(storage).totalRuns).toBe(7); });
 it('item data contains at least 30 loot items', async () => { const { ITEMS } = await import('../data/items'); expect(ITEMS.length).toBeGreaterThanOrEqual(30); });
});
