import type { RunState } from '../types';
import { allTiles, createBoard, neighbors, recomputeAdjacent } from './board';
import { adjustedMineCount, getExitThreshold, hasItem, markStartHints } from './effects';
import { int, shuffle, chance } from './rng';
export function initializeBoardForRun(run:RunState){ const mines=adjustedMineCount(run); run.board=createBoard(run.floorConfig.width,run.floorConfig.height,mines); }
export function generateBoard(run:RunState, firstX:number, firstY:number){ const board=run.board; const excludeDist=hasItem(run,'royal_survey')?2:1; const excluded=new Set<string>(); for(let y=firstY-excludeDist;y<=firstY+excludeDist;y++) for(let x=firstX-excludeDist;x<=firstX+excludeDist;x++) if(x>=0&&y>=0&&x<board.width&&y<board.height) excluded.add(`${x},${y}`);
 const candidates=shuffle(run.rng, allTiles(board).filter(t=>!excluded.has(`${t.x},${t.y}`))); for(const t of candidates.slice(0,board.mineCount)) t.kind='mine';
 const safe=shuffle(run.rng, allTiles(board).filter(t=>t.kind!=='mine'&&!excluded.has(`${t.x},${t.y}`))); const baseTreasures=run.player.floor<=3?2:run.player.floor<=6?3:4; const treasureCount=baseTreasures+(run.modifier.id==='greedy_goblins'?2:0); for(const t of safe.slice(0,treasureCount)){ t.kind='treasure'; t.trappedTreasure=run.modifier.id==='greedy_goblins'&&chance(run.rng,.25); }
 recomputeAdjacent(board); board.generated=true; board.firstClick=false; markStartHints(run); }
export function treasureGold(run:RunState){ const f=run.player.floor; const base=f<=3?int(run.rng,5,10):f<=6?int(run.rng,8,16):int(run.rng,12,24); return Math.floor(base * (1 + 0)); }
export function placeExitIfNeeded(run:RunState, log:string[]): boolean { const board=run.board; if(board.exitPlaced) return false; const safe=board.width*board.height-board.mineCount; const needed=Math.ceil(safe * getExitThreshold(run)); if(run.floorStats.revealedSafe < needed) return false; board.exitAvailable=true; const candidates=shuffle(run.rng, allTiles(board).filter(t=>!t.revealed&&!t.flagged&&t.kind==='normal')); if(!candidates.length){ run.status='won'; log.push('The exit opened under your feet.'); return true; } const exit=candidates[0]; exit.kind='exit'; board.exitPlaced=true; log.push('The exit has appeared somewhere below.'); if(hasItem(run,'cartographers_compass')){ const near=allTiles(board).filter(t=>t.kind!=='mine'&&Math.max(Math.abs(t.x-exit.x),Math.abs(t.y-exit.y))<=3); if(near.length) near[0].dangerMarked=true; log.push('The exit is somewhere near the marked region.'); } if(hasItem(run,'crown_deep_king')) for(const n of neighbors(board,exit.x,exit.y)) if(n.kind==='mine') n.dangerMarked=true; return true; }
