import type { RunState, TileState } from '../types';
import { getTile, neighbors } from './board';
import { applyMineDamage, getTreasureGoldMultiplier, hasItem, onSafeReveal } from './effects';
import { generateBoard, placeExitIfNeeded } from './generation';
export function revealTile(run:RunState,x:number,y:number,log:string[], safeMode=false): void { if(run.status!=='active') return; const tile=getTile(run.board,x,y); if(!tile||tile.flagged||tile.magneticFlagged||tile.revealed) return; if(!run.board.generated) generateBoard(run,x,y); const t=getTile(run.board,x,y)!; if(t.kind==='mine'){ if(safeMode){ t.dangerMarked=true; return; } t.revealed=true; applyMineDamage(run,t,log); return; } revealSafeRegion(run,t,log); placeExitIfNeeded(run,log); if(t.kind==='exit'&&t.revealed) clearFloor(run,log); }
export function revealSafeRegion(run:RunState, start:TileState, log:string[]){ const stack=[start]; const seen=new Set<string>(); while(stack.length){ const tile=stack.pop()!; const key=`${tile.x},${tile.y}`; if(seen.has(key)||tile.revealed||tile.flagged||tile.magneticFlagged||tile.kind==='mine') continue; seen.add(key); tile.revealed=true; onSafeReveal(run,tile,log); if(tile.kind==='treasure'){ const base=run.player.floor<=3?5+Math.floor((run.rng.seed%6+6)%6):run.player.floor<=6?8+Math.floor((run.rng.seed%9+9)%9):12+Math.floor((run.rng.seed%13+13)%13); const gold=Math.floor(base*getTreasureGoldMultiplier(run)); run.player.gold+=gold; run.floorStats.goldCollected+=gold; log.push(`You found ${gold} gold.`); if(tile.trappedTreasure) applyMineDamage(run,tile,log); if(hasItem(run,'gem_studded_pick')){ const adj=neighbors(run.board,tile.x,tile.y).find(n=>!n.revealed&&!n.flagged&&n.kind!=='mine'); if(adj) stack.push(adj); } }
 if(tile.kind==='exit'){ clearFloor(run,log); return; }
 if(tile.adjacentMines===0) for(const n of neighbors(run.board,tile.x,tile.y)) if(n.kind!=='mine') stack.push(n); }
}
export function clearFloor(run:RunState,log:string[]){ if(run.status!=='active') return; run.status='won'; log.push('Floor cleared.'); }
