import type { GameAction, GameState, RunState, SaveData } from '../types';
import { getFloorConfig } from '../data/floors';
import { ACTIVE_MODIFIERS, MODIFIERS } from '../data/modifiers';
import { ITEM_BY_ID } from '../data/items';
import { createBoard, neighbors } from './board';
import { makeSeed, pick, random } from './rng';
import { onStartFloor, addItem, onFloorClear, hasItem } from './effects';
import { initializeBoardForRun } from './generation';
import { revealTile } from './reveal';
import { toggleFlag } from './flag';
import { chordTile } from './chord';
import { generateRewards } from './loot';
import { buyItem, generateShop } from './shop';
import { DEFAULT_SAVE } from './persistence';
export const initialGameState: GameState = { phase:'menu', run:null, save:DEFAULT_SAVE, rewardChoices:[], shopItems:[], targetingMode:null, log:[] };
function log(state:GameState,msg:string){ return {...state, log:[msg,...state.log].slice(0,9)}; }
export function createRun(save:SaveData, seed=makeSeed()): RunState { const floorConfig=getFloorConfig(1); const run:RunState={player:{hp:3,maxHp:3,armor:0,gold:0,floor:1,items:[],flagsAvailable:null,revealCharges:0,scanCharges:0,rerolls:0,mistakesForgiven:0,score:0},board:createBoard(floorConfig.width,floorConfig.height,0),floorConfig,modifier:MODIFIERS[0],floorStats:{revealedSafe:0,damageTaken:false,luckyBootsUsed:false,hourglassUsed:false,carefulHandsUsed:false,runeUsed:false,trapEaterUsed:false,lastDescentUsed:false,insuranceUsed:false,unstableUsed:false,crackedCount:0,safeRevealsSinceArmor:0,goldCollected:0,minesTriggered:0},status:'active',rng:{seed},seed}; initializeBoardForRun(run); onStartFloor(run); return run; }
function nextFloor(run:RunState){ run.player.floor++; run.player.score+=50*run.player.floor; run.floorConfig=getFloorConfig(run.player.floor); run.modifier=random(run.rng)<run.floorConfig.modifierChance?pick(run.rng,ACTIVE_MODIFIERS):MODIFIERS[0]; run.status='active'; initializeBoardForRun(run); onStartFloor(run); }
function finishIfNeeded(state:GameState): GameState { const run=state.run; if(!run) return state; if(run.status==='lost'){ const save={...state.save,losses:state.save.losses+1,deepestFloor:Math.max(state.save.deepestFloor,run.player.floor),totalGoldCollected:state.save.totalGoldCollected+run.floorStats.goldCollected}; return {...state,phase:'gameOver',save, targetingMode:null}; }
 if(run.status==='won'){ onFloorClear(run); if(run.player.floor>=10){ run.player.score+=500; run.finalResult='victory'; const save={...state.save,wins:state.save.wins+1,deepestFloor:10,totalGoldCollected:state.save.totalGoldCollected+run.floorStats.goldCollected,unlockedItems:[...new Set([...state.save.unlockedItems,'rare','legendary'])]}; return {...state,phase:'gameOver',save,targetingMode:null}; }
 const save={...state.save,deepestFloor:Math.max(state.save.deepestFloor,run.player.floor),totalGoldCollected:state.save.totalGoldCollected+run.floorStats.goldCollected,unlockedItems:run.player.floor>=5?[...new Set([...state.save.unlockedItems,'rare'])]:state.save.unlockedItems}; return {...state,phase:'reward',save,rewardChoices:generateRewards(run,save),targetingMode:null,log:['Choose one relic.',...state.log].slice(0,9)}; }
 return state; }
export function gameReducer(state:GameState, action:GameAction): GameState { if(action.type==='LOAD_SAVE') return {...state,save:action.save}; if(action.type==='RETURN_TO_MENU') return {...state,phase:'menu',run:null,targetingMode:null}; if(action.type==='START_RUN'){ const save={...state.save,totalRuns:state.save.totalRuns+1}; return {phase:'playing',run:createRun(save),save,rewardChoices:[],shopItems:[],targetingMode:null,log:['The descent begins.']}; }
 const run=state.run; if(!run) return state; const messages=[...state.log]; switch(action.type){ case 'SET_TARGETING': return {...state,targetingMode:action.mode}; case 'CANCEL_TARGETING': return {...state,targetingMode:null}; case 'REVEAL_TILE': revealTile(run,action.x,action.y,messages); return finishIfNeeded({...state,run,log:messages,targetingMode:null}); case 'TOGGLE_FLAG': toggleFlag(run,action.x,action.y,messages); return {...state,run,log:messages}; case 'CHORD_TILE': chordTile(run,action.x,action.y,messages); return finishIfNeeded({...state,run,log:messages}); case 'USE_PROBE': if(run.player.revealCharges>0){ run.player.revealCharges--; revealTile(run,action.x,action.y,messages,true); messages.unshift('Probe completed.'); } return finishIfNeeded({...state,run,log:messages,targetingMode:null}); case 'USE_SCAN': if(run.player.scanCharges>0){ run.player.scanCharges--; const t=run.board.tiles[action.y]?.[action.x]; if(t){ const label=t.kind==='mine'?'mine':t.kind==='treasure'?'treasure':t.kind==='exit'?'exit':'safe'; t.scannedStatus=label; if(hasItem(run,'crystal_lens')) for(const n of [t,...neighbors(run.board,t.x,t.y)]) n.scannedStatus=n.kind==='mine'?'mine':n.kind==='treasure'?'treasure':n.kind==='exit'?'exit':'safe'; messages.unshift(`Scan: ${label}.`); } } return {...state,run,log:messages,targetingMode:null}; case 'REROLL_REWARD': if(run.player.rerolls>0){ run.player.rerolls--; return {...state,run,rewardChoices:generateRewards(run,state.save),log:['Reward rerolled.',...messages].slice(0,9)}; } return state; case 'CHOOSE_REWARD': addItem(run,action.itemId); if(action.itemId==='breakfast_ration') messages.unshift('Breakfast Ration restored 1 HP.'); if(run.player.floor===5) return {...state,phase:'shop',run,shopItems:generateShop(run,state.save),rewardChoices:[],log:messages}; nextFloor(run); return {...state,phase:'playing',run,rewardChoices:[],log:[`Floor ${run.player.floor} begins.`,...messages].slice(0,9)}; case 'BUY_ITEM': if(buyItem(run,action.itemId)) messages.unshift(`Bought ${ITEM_BY_ID[action.itemId].name}.`); return {...state,run,log:messages}; case 'CONTINUE_TO_NEXT_FLOOR': nextFloor(run); return {...state,phase:'playing',run,shopItems:[],log:[`Floor ${run.player.floor} begins.`,...messages].slice(0,9)}; default: return state; } }
